### ISSUE TITLE
Invalid memory address error

### ISSUE THREAD

**Issue by IngwiePhoenix** [tulir/mautrix-whatsapp#175] opened 2020-05-04 12:17 UTC
This seems to happenen every now and then, causing the service to crash and making me having to consider using something like forever to keep it running.

```
[May  1, 2020 22:28:33] [Matrix/@ingwiephoenix:ingwie.io/DEBUG] GET http://localhost:8008/_matrix/client/r0/sync?filter=5&set_presence=offline&since=s305864_13421283_17074_259125_161_122_200_36000_17&timeout=30000
[May  1, 2020 22:28:33] [User/@ingwiephoenix:ingwie.io/INFO] Marking online
[May  1, 2020 22:28:33] [User/@ingwiephoenix:ingwie.io/ERROR] WhatsApp error: connection to WhatsApp servers failed: websocket: close 1006 (abnormal closure): unexpected EOF
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x7a175f]

goroutine 39826 [running]:
github.com/Rhymen/go-whatsapp.(*Conn).Disconnect(0xc0002b4000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /root/go/pkg/mod/github.com/tulir/go-whatsapp@v0.2.6/conn.go:218 +0x7f
github.com/Rhymen/go-whatsapp.(*Conn).readPump.func1(0xc0002b4000)
        /root/go/pkg/mod/github.com/tulir/go-whatsapp@v0.2.6/read.go:21 +0x5a
github.com/Rhymen/go-whatsapp.(*Conn).readPump(0xc0002b4000)
        /root/go/pkg/mod/github.com/tulir/go-whatsapp@v0.2.6/read.go:40 +0x368
created by github.com/Rhymen/go-whatsapp.(*Conn).connect
        /root/go/pkg/mod/github.com/tulir/go-whatsapp@v0.2.6/conn.go:201 +0x3ab
```

Any idea what this is about?

**Comment by Rafaeltheraven** [comment] 2020-05-08 21:06
Seems to be a similar (if not the same) issue as I raised in #172

**Comment by tulir** [comment] 2020-06-25 13:46
Duplicate of #172

**Closed by tulir** 2020-06-25 13:46 UTC
Labels: duplicate
