### ISSUE TITLE
 WhatsApp error: unexpected websocket close: websocket: close 1006 (abnormal closure): unexpected EOF

### ISSUE THREAD

**Issue by gzlivre** [tulir/mautrix-whatsapp#35] opened 2019-02-22 18:57 UTC
Hi,
After a few minutes of starting the service mautrix-whatsapp, I believe that whatsapp is blocking my requests.
this is de log:
```
error writing to socket: write tcp [XXXX:xXXXX:XXXXX:XXXX:XXX]:53642->[2a03:2880:f204:c5:face:b00c:0:167]:443: write: connection reset by peer
[Feb 22, 2019 17:06:46] [User/@user:matrix.domain.org/ERROR] WhatsApp error: unexpected websocket close: websocket: close 1006 (abnormal closure): unexpected EOF
[Feb 22, 2019 17:06:47] [User/@user:matrix.domain.org/ERROR] WhatsApp error: unexpected websocket close: websocket: close 1006 (abnormal closure): unexpected EOF
[Feb 22, 2019 17:06:48] [User/@user:matrix.domain.org/ERROR] WhatsApp error: unexpected websocket close: websocket: close 1006 (abnormal closure): unexpected EOF
[Feb 22, 2019 17:06:49] [User/@user:matrix.domain.org/ERROR] WhatsApp error: unexpected websocket close: websocket: close 1006 (abnormal closure): unexpected EOF
[Feb 22, 2019 17:06:49] [User/@user:matrix.domain.org/ERROR] WhatsApp error: unexpected websocket close: websocket: close 1006 (abnormal closure): unexpected EOF
```
# OS version
```
# cat /etc/issue
Debian GNU/Linux 9 \n \l
```

# go version
```
:~# go version
go version go1.11.5 linux/amd64
```

# mautrix-whatsapp version
```
:~/mautrix-whatsapp# git pull
Already up-to-date.
```

**Comment by vorletzter** [comment] 2019-02-23 08:25
Its a bug in a Library: https://github.com/tulir/mautrix-whatsapp/issues/35

**Comment by babolivier** [comment] 2019-02-25 17:34
Also a duplicate of #21

**Comment by tulir** [comment] 2019-02-25 19:31
#21 is for normal closures (e.g. opening whatsapp web), this is a different issue that was probably temporarily fixed by downgrading go-whatsapp

**Comment by babolivier** [comment] 2019-02-25 19:40
Oh, my bad then.

**Comment by gzlivre** [comment] 2019-02-25 22:28
thanks to everyone
I will wait for the go-whatsapp update

**Comment by gzlivre** [comment] 2019-02-26 18:39
i pull the latests commits, and now its works perfect
maybe https://github.com/tulir/mautrix-whatsapp/commit/a5f5d93d9f21077e3801cee92a6e49239f78e5a6

**Comment by tulir** [comment] 2019-02-26 19:14
@gzlivre As I said, downgrading go-whatsapp fixed it temporarily, so 6dd83b3d30d68dc1626dca1b43ce93e3a6f1e672 and 485acf6de654b8fb70007876c074fb004eb9717b mostly

**Comment by gzlivre** [comment] 2019-02-26 19:24
@tulir, many thanks
great job!

**Closed** 2019-03-13 23:15 UTC
Labels: bug, external
