### ISSUE TITLE
message sending responded with %!d(float64=400) when sending image

### ISSUE THREAD

**Issue by t0stiman** [tulir/mautrix-whatsapp#168] opened 2020-04-13 16:13 UTC
When sending an image, I get the following error:

    Your message may not have been bridged: message sending responded with %!d(float64=400)

log:
```
[Apr 13, 2020 16:06:10] [Portal/CENSORED@s.whatsapp.net-31657460255@s.whatsapp.net/DEBUG] Received event $vuElfUxTvEGOon93x7Z1jBEphZ4ciLCwGhQ8GCt1q-0
[Apr 13, 2020 16:06:10] [Portal/CENSORED@s.whatsapp.net-31657460255@s.whatsapp.net/DEBUG] Sending event $vuElfUxTvEGOon93x7Z1jBEphZ4ciLCwGhQ8GCt1q-0 to WhatsApp
[Apr 13, 2020 16:06:11] [Portal/CENSORED@s.whatsapp.net-31657460255@s.whatsapp.net/ERROR] Error handling Matrix event $vuElfUxTvEGOon93x7Z1jBEphZ4ciLCwGhQ8GCt1q-0: message sending responded with %!d(float64=400)
[Apr 13, 2020 16:06:11] [Matrix/@whatsapp_CENSORED:matrix.CENSORED.com/DEBUG] PUT https://matrix.CENSORED.com/_matrix/client/r0/rooms/%21JSaNeYlzgVmeQJnZBU:matrix.CENSORED.com/send/m.room.message/go158679397143588275113?user_id=%40whatsapp_CENSORED%3Amatrix.CENSORED.com {"msgtype":"m.notice","body":"⚠ Your message may not have been bridged: message sending responded with %!d(float64=400)"}
```

What does this error mean? Are we inserting a float64 into an integer?

**Comment by thomcatdotrocks** [comment] 2020-04-26 17:10
I am only getting this when trying to send a GIF.  It looks like the "/mms/gif" path/work still needs to be added to `go-whatsapp`.

**Comment by BVerdoes** [comment] 2020-04-27 17:20
> I am only getting this when trying to send a GIF. It looks like the "/mms/gif" path/work still needs to be added to `go-whatsapp`.

I got this error when sending .jpg .png images.

**Comment by tulir** [comment] 2020-06-23 13:36
Duplicate of #141 (the problem is lack of gif->mp4 conversion, not a problem in go-whatsapp)

**Closed by tulir** 2020-06-23 13:36 UTC
Labels: duplicate
