### ISSUE TITLE
Bridge explodes if connectivity fails

### ISSUE THREAD

**Issue by ara4n** [tulir/mautrix-whatsapp#49] opened 2019-03-14 14:17 UTC
```
[Mar 12, 2019 12:06:24] [User/@matthew:arasphere.net/ERROR] WhatsApp error: unexpected websocket close: websocket: close 1000 (normal)
[Mar 12, 2019 12:06:25] [User/@matthew:arasphere.net/ERROR] WhatsApp error: unexpected websocket close: websocket: close 1000 (normal)
[Mar 12, 2019 12:06:26] [User/@matthew:arasphere.net/ERROR] WhatsApp error: unexpected websocket close: websocket: close 1000 (normal)
panic: repeated read on failed websocket connection

goroutine 75 [running]:
github.com/gorilla/websocket.(*Conn).NextReader(0xc000020160, 0x116dde0, 0xc000091312, 0x2, 0xc00009e000, 0xc0002ffb00)
        /home/matrix/go/pkg/mod/github.com/gorilla/websocket@v1.4.0/conn.go:967 +0x356
github.com/gorilla/websocket.(*Conn).ReadMessage(0xc000020160, 0xa135c0, 0xc000422790, 0x1, 0x1, 0xb56280, 0xc000422790)
        /home/matrix/go/pkg/mod/github.com/gorilla/websocket@v1.4.0/conn.go:1028 +0x2f
github.com/Rhymen/go-whatsapp.(*Conn).readPump(0xc00026e1a0)
        /home/matrix/go/pkg/mod/github.com/!rhymen/go-whatsapp@v0.0.0-20190208090600-c1173899de99/conn.go:272 +0x73
created by github.com/Rhymen/go-whatsapp.NewConn
        /home/matrix/go/pkg/mod/github.com/!rhymen/go-whatsapp@v0.0.0-20190208090600-c1173899de99/conn.go:129 +0x1ff
```

similar but not the same as #18

**Comment by tulir** [comment] 2019-03-14 15:08
Duplicate of #21. It might actually be fixable now that go-whatsapp has a `Disconnect()` function.

**Closed by tulir** 2019-03-14 15:08 UTC
Labels: duplicate
