### ISSUE TITLE
Occasional seg fault

### ISSUE THREAD

**Issue by alistair23** [tulir/mautrix-whatsapp#198] opened 2020-06-13 04:17 UTC
Every few days the bridge will seg fault. This is the information from the fault. Let me know what other details you would like:

```
[Jun 12, 2020 20:24:39] [User/@alistair23:matrix.alistair23.me/ERROR] WhatsApp error: k
eepAlive failed: connection timed out
[Jun 12, 2020 20:31:22] [User/@alistair23:matrix.alistair23.me/DEBUG] JSON message: ["S
tream","asleep"]
[Jun 12, 2020 21:23:05] [User/@alistair23:matrix.alistair23.me/ERROR] WhatsApp error: c
onnection to WhatsApp servers failed: websocket: close 1006 (abnormal closure): unexpec
ted EOF
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x79be2f]

goroutine 18845 [running]:
github.com/Rhymen/go-whatsapp.(*Conn).Disconnect(0xc000336000, 0x0, 0x0, 0x0, 0x0, 0x0,
 0x0, 0x0, 0x0, 0x0, ...)
        /home/alistair/mautrix-whatsapp/go/work/pkg/mod/github.com/tulir/go-whatsapp@v0
.2.8/conn.go:218 +0x7f
github.com/Rhymen/go-whatsapp.(*Conn).readPump.func1(0xc000336000)
        /home/alistair/mautrix-whatsapp/go/work/pkg/mod/github.com/tulir/go-whatsapp@v0
.2.8/read.go:21 +0x5a
github.com/Rhymen/go-whatsapp.(*Conn).readPump(0xc000336000)
        /home/alistair/mautrix-whatsapp/go/work/pkg/mod/github.com/tulir/go-whatsapp@v0
.2.8/read.go:40 +0x34d
created by github.com/Rhymen/go-whatsapp.(*Conn).connect
        /home/alistair/mautrix-whatsapp/go/work/pkg/mod/github.com/tulir/go-whatsapp@v0
.2.8/conn.go:201 +0x376
```

**Comment by vmario89** [comment] 2020-06-23 11:58
same here, problem occures weekly for about one year now. seems to be some core problem :-(

```
● mautrix-whatsapp.service - Mautrix WhatsApp Service
  2    Loaded: loaded (/opt/matrix-bridges/mautrix-whatsapp/mautrix-whatsapp.service; enabled; vendor preset: enabled)
  3    Active: active (exited) (Result: exit-code) since Fr 2020-06-19 22:54:21 CEST; 3 days ago
  4   Process: 9357 ExecStart=/opt/matrix-bridges/mautrix-whatsapp/mautrix-whatsapp (code=exited, status=2)
  5  Main PID: 9357 (code=exited, status=2)
  6    CGroup: /system.slice/mautrix-whatsapp.service
  7
  8 Jun 23 02:54:31 h2606131.stratoserver.net mautrix-whatsapp[9357]: [Jun 23, 2020 02:54:31] [Portal/33781883993-1531993027@g.us/INFO    ] Syncing portal for @
  9 Jun 23 02:54:31 h2606131.stratoserver.net mautrix-whatsapp[9357]: panic: runtime error: invalid memory address or nil pointer dere    ference
 10 Jun 23 02:54:31 h2606131.stratoserver.net mautrix-whatsapp[9357]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7    a914e]
 11 Jun 23 02:54:31 h2606131.stratoserver.net mautrix-whatsapp[9357]: goroutine 23241 [running]:
 12 Jun 23 02:54:31 h2606131.stratoserver.net mautrix-whatsapp[9357]: github.com/Rhymen/go-whatsapp.(*Conn).write(0xc00039a000, 0x1, 0    xc003d94900, 0x11, 0xc000262cd0, 0x49, 0x50, 0x0, 0xc003966000, 0x7f4036ef2d98)
 13 Jun 23 02:54:31 h2606131.stratoserver.net mautrix-whatsapp[9357]:         /root/go/pkg/mod/github.com/tulir/go-whatsapp@v0.2.6/wri    te.go:130 +0x3e
 14 Jun 23 02:54:31 h2606131.stratoserver.net mautrix-whatsapp[9357]: github.com/Rhymen/go-whatsapp.(*Conn).writeJson(0xc00039a000, 0x    c003602240, 0x3, 0x3, 0x0, 0x0, 0x0)
 15 Jun 23 02:54:31 h2606131.stratoserver.net mautrix-whatsapp[9357]:         /root/go/pkg/mod/github.com/tulir/go-whatsapp@v0.2.6/wri    te.go:33 +0x32d
 16 Jun 23 02:54:31 h2606131.stratoserver.net mautrix-whatsapp[9357]: github.com/Rhymen/go-whatsapp.(*Conn).GetGroupMetaData(...)
 17 Jun 23 02:54:31 h2606131.stratoserver.net mautrix-whatsapp[9357]:         /root/go/pkg/mod/github.com/tulir/go-whatsapp@v0.2.6/gro    up.go:14
```

**Comment by tulir** [comment] 2020-06-25 13:46
Duplicate of #172

**Closed by tulir** 2020-06-25 13:46 UTC
Labels: duplicate
