### ISSUE TITLE
Use spaces to store WhatsApp contacts and groups

### ISSUE THREAD

**Issue by frandavid100** [tulir/mautrix-whatsapp#306] opened 2021-05-24 17:00 UTC
Every time I've recommended the WhatsApp bridge to a new user, the thing they liked the least has been having to use the bot in order to start a chat. But now that we have spaces, it doesn't need to be like that anymore.

Instead, after logging in to the user's WhatsApp account, the bot could create DMs for every one of the user's contacts and place all those DMs (as well as bridged rooms) inside a "WhatsApp" space.

That would allow the user to find all their WhatsApp contacts easily, and start conversations without having to run any commands.

**Comment by tulir** [comment] 2021-05-24 17:02
Duplicate of #296

**Closed by tulir** 2021-05-24 17:02 UTC
